behaviors:
  Volleyball:
    trainer_type: poca
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 60000000
    time_horizon: 1000
    summary_freq: 20000